### ISSUE TITLE
NIArms All in One pack

### ISSUE THREAD

**Issue by mollybeam** [TaskForceAthena/TFA-Modlists#2]
https://steamcommunity.com/workshop/filedetails/?id=665702172

Weapons from this pack could be used to fill gaps where one would expect certain weapons in a modern context e.g. G3, AUG 
Also, I really want my bright pink stubby 416. 

High quality sounds and textures all-round, though back in 2019 some of the weapon weights were scuffed. I believe this is fixed now though.

**Comment by Shepherd932** [comment]
it has my approval

**Comment by chrisinthailand** [comment]
The only issue I see would be people having too MUCH choice in the arsenal and spending an inordinate amount of time at mission start trying to work out which weapon from which mod they want, especially since there are liely tp be multiple duplicates of popular weapons systems with RHS, NiARMS et al. 

We might need to think about instigating some method of deciding on a limited arsenal by asking all members to give us a list of up to three personal favorite weapons from the full mods list so we can narrow it down to what is requested / required.

**Comment by chrisinthailand** [comment]
ie; one main weapon, one side arm and one launcher choice per person. That would also ease training requirements if we have a defined set of, for instance, launchers, that we would be using.

**Comment by mollybeam** [comment]
> Multiple duplicates of popular weapons

It's a pack full of standalone mods, so we can pack and choose which ones we use

**Comment by mollybeam** [comment]
Added a new NIArms All-In-One
